name: "SonarQube Code Scanner"
on:
  pull_request:
    branches:
      - main
jobs:
  sonarqube-job:
    name: SonarQube Code Scanner
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube
        env:
          SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
        ports:
          - 9000:9000
container:
  image: sonarsource/sonar-scanner-cli
  env:
    fail_build: "false"
    component: "dehaat_repository"
    sonar_url: "http://sonarqube:9000"
    sonar_username: "admin"
    sonar_password: "admin"
    slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
    slack_channel: "C0390TN4CK1"
  
  steps:
    - name: Check out repository code
      uses: actions/checkout@v2
  
    - name: Run sonarqube scanner
      run: sonar-scanner
        -Dsonar.projectKey=dehaat_repository
        -Dsonar.sources=$GITHUB_WORKSPACE
        -Dsonar.host.url=http://sonarqube:9000
        -Dsonar.login=admin
        -Dsonar.password=admin
    
    - name: Install SonarReport
      run: npm install -g sonar-report

    - name: Fail Build and Send Slack Report
      run: curl -s https://raw.githubusercontent.com/sttor/remote-scripts/main/sonarqube-slack-report.py | python3
